# Generated by Django 2.2.1 on 2019-05-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alg_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='groupalgorithm',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='algorithm',
            name='chpu',
            field=models.CharField(blank=True, max_length=200, verbose_name='ЧПУ'),
        ),
    ]
