# Generated by Django 2.2.1 on 2019-05-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alg_list', '0002_auto_20190506_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='chpu',
            new_name='slug',
        ),
    ]
