# Generated by Django 2.2.1 on 2019-05-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alg_list', '0004_groupalgorithm_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'ordering': ['id'], 'verbose_name': 'Название алгоритма', 'verbose_name_plural': 'Алгоритмы'},
        ),
        migrations.AlterModelOptions(
            name='groupalgorithm',
            options={'ordering': ['id'], 'verbose_name': 'Название группы', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='groupalgorithm',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
